### ISSUE TITLE
Integrar nuevos servicios necesidades_crud a cliente

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades_cliente#116]
Se solicita:

- [x] Ajustar ngModel al formulario de solicitud de necesidad :necktie: 

- [x] Armar el objeto _trNecesidad_ en el controlador para que sea enviado al MID :abcd:

**Comment by Soulfilip-UD** [comment]
Tarea revisada y se contempla los cambios en el comportamiento del sistema actualmente,

Proceeding to close Issue 👾
