### ISSUE TITLE
Ajustes necesidades

### ISSUE THREAD

**Issue by DianaPatriciaRamirez** [udistrital/necesidades_cliente#156]
En revisión del 15 de noviembre se encuentran las siguientes observaciones. Se espera revisar el módulo totalmente terminado el martes 19 de noviembre.

- [x] Actualizar datos de los rubros.
- [x] Justificar valores a la derecha, de actividades.
- [x] Agregar alerta, de documento agregado en marco legal.
- [x] Los valores del “Valor Unitario” debe estar justificados al lado derecho.
- [x] Revisar error en formulario de compra.
- [x] No debe permitir financiación en ceros.

**Comment by macaguegi** [comment]
Se solicitan estos ajustes : 
- [ ] Agregar requisitos mínimos para PRESTACIÓN DE SERVICIOS . Similar a actividades específicos.

- [ ] Revisar el registro de solicitudes en simultaneo.

- [ ] Mostrar el detalle de Clase de Contratación . Definir que atributos se deberían mostrar (Ing. Diana G)
CPS : Perfil y Requisitos mínimos

- [ ] Opción para guardar necesidad en borrador . Ubicar un botón de GUARDAR en la parte inferior del formulario

**Comment by Soulfilip-UD** [comment]
- [ ] Revisar con Viviana la alineación de los textos
<img width="1132" alt="Screen Shot 2019-11-27 at 10 41 45 AM" src="https://user-images.githubusercontent.com/50924615/69737700-d9ce3c80-1102-11ea-973f-6ef0557f1d7d.png">

**Comment by DianaPatriciaRamirez** [comment]
En revisión del 29 de noviembre, ya queda el modulo terminado: 

- [ ] El botón "REQUISITO MINIMO" dejar en mayúsculas.

- [ ] Realizar ultima revisión funcional por parte del equipo de desarrollo y dejar modulo congelado 2 días antes de revisión con usuario.

**Comment by Soulfilip-UD** [comment]
Se revisan los últimos ajustes en la reunión del martes 3 Diciembre a las 10 am

**Comment by Soulfilip-UD** [comment]
- [ ] En el formulario de productos, requerir los campos con validadción

- [ ] El listado de productos de compra , alimentarse del API de ARKA

Una vez listo adjuntar screenshot , ya que el el sistema se enviara  a revisión por el usuario de una vez

**Comment by DianaPatriciaRamirez** [comment]
Se comparte el modelo de datos y la dirección para usar el API de catálogo de elementos que está actualmente para ARKA II.

Modelo de datos: https://user-images.githubusercontent.com/23342808/68551355-22cf8280-03da-11ea-8c25-4cb053a1513b.png

Endpoint del servicio:

    http://pruebasapi.intranetoas.udistrital.edu.co:8120/
    https://autenticacion.portaloas.udistrital.edu.co/apioas/catalogo_elementos_crud/v1

**Comment by mcrubianot** [comment]
De acuerdo a la reunión sostenida en horas de la mañana del día de hoy 3/12/2019 se procedió a realizar la revisión de los desarrollos de necesidades asi:

Contratación/Duración/funcionamiento/compra:
Solicitud de necesidad 54 
Necesidad 114 
Solicitud de cdp 29

Servicios Públicos: 
Solicitud de necesidad 55 
Necesidad 115 
Solicitud de cdp 30

Contratación/pago único/ Supervisor / inversión:
Solicitud de necesidad 56
Necesidad 116
Solicitud de cdp 31

Servicio/duración/funcionamiento
Solicitud de necesidad 57
Necesidad 117
Solicitud de cdp 32

Compra y servicio/duración/funcionamiento
Solicitud de necesidad 58
Necesidad 118
Solicitud de cdp 33

- [ ] Considero pertinente revisar que al momento en que me falte algún dato, resalte cual es el dato que me hace falta

- [ ] Al momento de hacer las consultas, en la pantalla que se me genera debe incluirse el subtotal de lo adquirido ya que solamente está el iva y el total.

**Comment by Soulfilip-UD** [comment]
Se está validando y se anexa el texto que comunica que los campos son requeridos
<img width="1316" alt="Screen Shot 2019-12-06 at 12 02 32 AM" src="https://user-images.githubusercontent.com/50924615/70297425-01d13600-17bc-11ea-99ad-ed6cffb5ae39.png">
Se conecto al catalogo de Arka
<img width="542" alt="Screen Shot 2019-12-06 at 12 03 27 AM" src="https://user-images.githubusercontent.com/50924615/70297443-11507f00-17bc-11ea-963c-b14043f1976e.png">
<img width="1222" alt="Screen Shot 2019-12-06 at 12 02 52 AM" src="https://user-images.githubusercontent.com/50924615/70297444-11e91580-17bc-11ea-9eac-21e1aa77c011.png">

Cambios realizados y revisados

**Comment by Soulfilip-UD** [comment]
Se cuenta con todos los ajustes requeridos en el Issue 👍 

Tarea finalizada
Proceeding to close Issue 👾
