### ISSUE TITLE
Asignación de roles que visualiza cada usuario - Necesidades cliente

### ISSUE THREAD

**Issue by Soulfilip-UD** [udistrital/necesidades_cliente#166]
Usuarios
-[ ] Vice Administrativa
-[ ] Presupuesto
-[ ] Planeación

Pedir usuarios de prueba con diferentes roles

**Comment by mcrubianot** [comment]
Se relaciona a continuación un archivo que fue levantado durante la vigencia 2018 que puede servir de base para el tema de los roles de los usuarios a ingresar al sistema Kronos.

https://docs.google.com/spreadsheets/d/1CxzZ2EaExl4pRMi5L_pCfaCpJgE-tvN4OLQaYHx1Eqw/edit?folder=0B8NdjGOtWwjCT05iZGhZZ2p5dzQ#gid=0

**Comment by Soulfilip-UD** [comment]
Recibo el siguiente documento: [documento roles](https://docs.google.com/spreadsheets/d/1CxzZ2EaExl4pRMi5L_pCfaCpJgE-tvN4OLQaYHx1Eqw/edit?folder=0B8NdjGOtWwjCT05iZGhZZ2p5dzQ#gid=0)

Con el cual debo cruzar los roles de WSO2 y agregar los cambios al menu desde [pruebasconfiguracion ](https://pruebaspresupuesto.portaloas.udistrital.edu.co/#/pages/dashboard)

Tarea en un 30 %

**Comment by Soulfilip-UD** [comment]
AL final del documento se adjunta el texto: 
<img width="1079" alt="Screen Shot 2020-01-17 at 1 06 46 AM" src="https://user-images.githubusercontent.com/50924615/72588265-b7b49780-38c5-11ea-860a-3d3f505a6924.png">

Por lo que no quedan claro los roles de los usuarios que intervienen en el modulo de necesidades, se asume que existen rol:
- Jefe de dependencia
- Secretaria
- Analista
- Vicerrector Academico
- Vicerrector Administrativo

Ya que no se puede confirmar la tarea queda congelada y el Issue se vuelve abrir cuando se cuente con la información.
