### ISSUE TITLE
Implementar interfaz unica en necesidades

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_cliente#169]
- [x] gestionar proceso con equipo core para implementar interfaz unica y realizar pruebas de la misma

**Comment by Soulfilip-UD** [comment]
Se integra el cliente de necesidades con la interfaz única , hay grandes aportes por parte de @CarlosGutierrezArdila  en el drone 
<img width="610" alt="Screen Shot 2019-12-05 at 11 44 29 PM" src="https://user-images.githubusercontent.com/50924615/70296632-460f0700-17b9-11ea-8f85-68d3a5538226.png">
<img width="905" alt="Screen Shot 2019-12-05 at 11 44 59 PM" src="https://user-images.githubusercontent.com/50924615/70296633-460f0700-17b9-11ea-8d10-74345ac9b15f.png">
<img width="1355" alt="Screen Shot 2019-12-05 at 11 46 58 PM" src="https://user-images.githubusercontent.com/50924615/70296803-8ff7ed00-17b9-11ea-9ddf-0c5335b84765.png">

**Comment by Soulfilip-UD** [comment]
Todo OK , se puso la :10:

Tarea revisada y finalizada
Proceeding to close Issue 👾
