### ISSUE TITLE
Recomendaciones del usuario final - 1ra presentación del módulo de necesidades 

### ISSUE THREAD

**Issue by DianaPatriciaRamirez** [udistrital/necesidades_cliente#174]
De acuerdo a la reunión celebrada el día de ayer 9 de diciembre en la cual se expuso el módulo de necesidades a los usuarios, se recopilaron las siguientes recomendaciones para ser tenidas en cuenta por el equipo de desarrollo del Proyecto Kronos: @CarlosGutierrezArdila 

- [x] Al observar el detalle de la necesidad generada, no está mostrando los datos de los elementos como son: nombre elemento, valor IVA, valor total; para los casos de compra y servicios o servicio. Gestionar antes del 13 de diciembre. Ver: 
![Captura de pantalla de 2019-12-10 10-07-13-2](https://user-images.githubusercontent.com/50375674/70550861-6be33580-1b44-11ea-873e-b0ae0b744121.png)

- [x] Para los contratos de prestación de servicios, cambiar "Estudio de mercados" por "Estudios previos". Gestionar antes del 13 de diciembre. 

- [x] Debe ser posible seleccionar las opciones de único pago y hasta agotar presupuesto al mismo tiempo, en el apartado "Duración de Necesidad". Gestionar antes del 13 de diciembre. 

- [x] Después de que la analista de requerimientos haya levantado esta información, para los contratos de prestación de servicios que sean de régimen común, el sistema debe incluir automáticamente el IVA. Se debe crear esta condición.

**Comment by DianaPatriciaRamirez** [comment]
Por otra parte, también quedaron las siguientes observaciones para ser analizadas y/o revisadas con los usuarios por parte de la analista de requerimientos: @mcrubianot 

- [ ] Definir cuántos salarios mínimos equivale a régimen común? Si no es por salarios mínimos, definir condición. Que tipo de porcentaje de IVA se debe aplicar. Actualizar HU.

- [ ] La Oficina Asesora de Planeación tiene un listado de productos definido al inicio de cada vigencia, por lo que es necesario definir qué usuario va a alimentar o actualizar dicha información en el sistema? Cómo se va a realizar ese procedimiento para actualizar esa información anualmente. Se debe aclarar al usuario que esto se debe realizar mediante el sistema y que la Oficina Asesora de Sistemas queda exonerada de cargar esa información de manera manual. Crear o actualizar HU.

- [ ] Revisar con Jurídica, cuál base de datos se debe utilizar para alimentar los datos correspondientes al "Código Actividad Económica"? Que usuario lo va a actualizar? Se debe aclarar al usuario que esto se debe realizar mediante el sistema y que la Oficina Asesora de Sistemas queda exonerada de cargar esa información de manera manual. Crear o actualizar HU.

- [ ] El usuario de la Oficina Asesora de Planeación recomienda se incluyan los porcentajes de los productos desde la necesidad, sin embargo, es necesario que se levante esta información sin comprometernos con este desarrollo puesto que cambiaría lo realizado hasta la fecha, teniendo en cuenta que tocaría incluir los porcentajes por meta para cada producto. Esto es un desarrollo nuevo para otra fase del proyecto y depende de los requerimientos que solicite la Oficina Asesora de Planeación puesto que también se incluiría el tema de plan de adquisiciones, los cuales no están contemplados a realizar dentro del proyecto Kronos o hasta que la OAP nos indique por escrito que necesita este desarrollo.

**Comment by mcrubianot** [comment]
Con respecto a las observaciones, me permito hacer las siguientes aclaraciones:

- [ ] Definir cuántos salarios mínimos equivale a régimen común? Si no es por salarios mínimos, definir condición. Que tipo de porcentaje de IVA se debe aplicar. Actualizar HU.- 

Para la vigencia 2019 el valor del ingreso para convertirse en régimen común es de $119.945.000
Estos datos cambian cada año razón por la cual se debe tener actualizado el dato de parámetros de gobierno que hace referencia tanto al valor de la UVT como de la cantidad de salarios mínimos que catalogan a una persona perteneciente del régimen común.

- [ ] Después de que la analista de requerimientos haya levantado esta información, para los contratos de prestación de servicios que sean de régimen común, el sistema debe incluir automáticamente el IVA. Se debe crear esta condición.

La historia de usuario no es necesario HU - 22 A 24 - Registrar, consultar y Aprobar Solicitud de Necesidad V3 no es necesario ajustarla toda vez que desde un principio se estableció que a los contratos de prestación de servicios se les debería calcular el IVA.

- [ ] La Oficina Asesora de Planeación tiene un listado de productos definido al inicio de cada vigencia, por lo que es necesario definir qué usuario va a alimentar o actualizar dicha información en el sistema? Cómo se va a realizar ese procedimiento para actualizar esa información anualmente. Se debe aclarar al usuario que esto se debe realizar mediante el sistema y que la Oficina Asesora de Sistemas queda exonerada de cargar esa información de manera manual. Crear o actualizar HU.

En la historia de usuario está desde un principio está establecido que la Oficina Asesora de Planeación es la encargada de alimentar esta información. No es necesario ajustar la HU por que ya estaba definido.

- [ ] Revisar con Jurídica, cuál base de datos se debe utilizar para alimentar los datos correspondientes al "Código Actividad Económica"? Que usuario lo va a actualizar? Se debe aclarar al usuario que esto se debe realizar mediante el sistema y que la Oficina Asesora de Sistemas queda exonerada de cargar esa información de manera manual. Crear o actualizar HU.

Es preciso aclarar que la Oficina Asesora Jurídica comentó que consideran necesario que los datos acá establecidos se ajuste a lo que tiene establecido la Dían. Para mayor comprensión los Códigos CIIU están establecido como un parámetro para efectos del control y determinación de los impuestos y demás obligaciones tributarias, aduaneras y cambiarías administradas por la Dirección de Impuestos y Aduanas Nacionales - DIAN.

Es un parámetro deberá utilizarse de manera obligatoria por todas las entidades de carácter privado o público que produzcan información estadística identificando la actividad económica principal
para la asignación correcta del código, de acuerdo con lo que establece la norma.

Es por ello que me permito sugerir que estos datos sean incluidos dentro de "Parámetros de Gobierno", teniendo en cuenta que esto no debe ser alimentado por el usuario, ya que los cambios de estos datos no son constantes.

No se requiere cambiar la historia de usuario por que este dato ya está siendo establecido.







--

**Comment by Soulfilip-UD** [comment]
Ajustes realizados

tarea Finalizada
Proceeding to close Issue 👾
