### ISSUE TITLE
Actualización de README

### ISSUE THREAD

**Issue by NeiderFajardo** [udistrital/necesidades_cliente#188]
Se realiza la actualización del README del repositorio, agregando la sección de vigencia: #187 y agregando un documento con toda la información de la licencia de forma detallada: #186 
Queda pendiente la revisión por parte del lider técnico @Soulfilip-UD

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial, tanto de este Issue como de los PRs citados
