### ISSUE TITLE
Realizar Solicitudes de infraestructura y base de datos para desplegar necesidades en PROD

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/necesidades_cliente#203]
se requiere realizar las diferentes solicitudes para el despliegue del aplicativo de necesidades en producción:  

- [x] despliegue de apis

- [x] despliegue de base de datos.

- [x] despliegue del cliente

**Comment by BOTOOM** [comment]
se realiza la solicitud para la preparación de la infraestructura el cliente

https://tuleap.udistrital.edu.co/plugins/tracker/?aid=38449

**Comment by BOTOOM** [comment]
se realiza la consulta de procedimiento para desplegar base de datos de postgres y mongo y se esta a espera de una respuesta

**Comment by BOTOOM** [comment]
se realizan ajustes para desplegar el cliente en master y es exitoso ahora el ingeniero fernando procederá a realizar ajustes en aws

**Comment by BOTOOM** [comment]
el cliente queda desplegado en el siguiente link

necesidades.portaloas.udistrital.edu.co

**Comment by BOTOOM** [comment]
los script de base de datos para las apis de : 
- movimientos_crud.
- necesidades_crud.
- plan_cuentas_crud.

eta escritos en archivos de go por ende para pasar a prod seria necesario sacarlos de esos archivos lo cual sera un trabajo manual, esto se consultara con los DBA.

se sigue en espera de que se levante la base de datos de mongo.

para el api de catalogo_elementos_crud se comunicara la solicitud al equipo de arka

**Comment by BOTOOM** [comment]
es necesario extraer los archivos de migraciones ya que estaban dichas sentencias en archivos de go lo cual se expresa en el [issue 42](https://github.com/udistrital/necesidades_crud/issues/42) del repositorio de necesidades_crud.

luego de ello se montan los siguientes kamban de petición de las bases de datos

- peticion de necesidades_crud : https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=38692
- peticon de movimientos_crud : https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=38693

**Comment by BOTOOM** [comment]
las base de datos fueron desplegadas en prod

**Comment by BOTOOM** [comment]
se realizan las solicitudes de despliegue de apis para:

- necesidades_crud: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=38712
- movimientos_crud: https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=38712

**Comment by BOTOOM** [comment]
se nos informa que la base de datos de mongo ya esta arriba por ende se solicitan unas variables d e entorno para hacer la solicitud d elas apis en prod

**Comment by BOTOOM** [comment]
api de movimientos crud manda error debido a que es posible que en el parameter store no se encuentre la contraseña

**Comment by BOTOOM** [comment]
mismo error del comentario anterior puede pasar para cuentas contables en prod

**Comment by BOTOOM** [comment]
mismo error para plan_cuentas_mongo_crud.


se solicitara a los dba la adicion de esas variables

**Comment by BOTOOM** [comment]
movimientos crud ya funciona en prod :smile:

**Comment by BOTOOM** [comment]
se ajusta cuentas contables crud para que funcione en prod https://hubci.portaloas.udistrital.edu.co/udistrital/cuentas_contables_crud/113

**Comment by BOTOOM** [comment]
se ajusta el api de plan cuentas mongo crud para que funcione correctamente en prod

https://hubci.portaloas.udistrital.edu.co/udistrital/plan_cuentas_mongo_crud/184

**Comment by BOTOOM** [comment]
se realiza solicitud de despliegue para plan cuentas mid y se espera que esta sea la ultima api que falte por desplegar

https://tuleap.portaloas.udistrital.edu.co/plugins/tracker/?aid=39416

**Comment by BOTOOM** [comment]
tambien presenta problemas el api de parametros gobierno

**Comment by BOTOOM** [comment]
parece que las apis estan desplegadas pero no actualizadas

**Comment by BOTOOM** [comment]
@corio27

**Comment by BOTOOM** [comment]
analizando con el ingeniero @corio27 se realizara lo siguiente

- mover data de impuestos a parámetros
- se usa el área de conocimiento de parámetros y es necesario cargar las demás áreas de conocimiento diferentes a colciencias
- se moverá unidades en data y endpoint a aprametros
- la modalidad de selección se moverá con endpoint y datos a parametros

**Comment by corio27** [comment]
para áreas de conocimiento utilizar tipo_parametro 4 'https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros/v1/parametro?query=TipoParametroId%3A4'

**Comment by corio27** [comment]
para las unidades de medida modificar el tipo de parámetro de acuerdo a 
 
5 longitud
6 masa
7 tiempo
8 capacidad
9 volumen
10 superficie

**Comment by corio27** [comment]
para modalidad de selección el tipo de parametro es 11
