### ISSUE TITLE
modificar el consumo de servicios en necesidades

### ISSUE THREAD

**Issue by BOTOOM** [udistrital/necesidades_cliente#228]
en el issue #203 se realiza la gestión del despliegue de necesidades en producción y el listado de los errores.

al final del issue se pueden encongtrar el listado de las 4 peticiones que fallan, dichas peticiones no fallan en ambiente de pruebas pero si en produccion, por ello el ingeniero jhon castellanos ha proporcionado esa información en el api de parámetros.

en el issue ya nombrado se nombran las soluciones planteadas, por ello se debe de consumir el api de parámetros y reemplazar las peticiones que generan error

**Comment by ManuelMurillo** [comment]
Teniendo en cuenta los endpoints asociados que tenian error:

- https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros_gobierno/v1/vigencia_impuesto/?limit=-1&query=Activo:true

- https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros_gobierno/v1/area_conocimiento/?limit=-1&query=Activo%3Atrue

- https://autenticacion.portaloas.udistrital.edu.co/apioas/administrativa_amazon_api/v1/unidad?limit=-1&sortby=Unidad&order=asc

- https://autenticacion.portaloas.udistrital.edu.co/apioas/administrativa_crud_api/v1/modalidad_seleccion/?limit=-1&sortby=NumeroOrden&order=asc

se ajustan de la siguiente forma con el api de parametros:

Para area_conocimiento:
- https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros/v1/parametro?query=TipoParametroId:4&limit=-1

Para Unidad:
- https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros/v1/parametro?query=TipoParametroId.AreaTipoid.Id:4&limit=-1

Para Modalidad de Seleccion:
- https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros/v1/parametro?query=TipoParametroId:11&limit=-1

Para Vigencia Impuesto:
- https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros/v1/parametro?query=TipoParametroId:12&limit=-1

**Comment by BOTOOM** [comment]
se realiza la inserción de los núcleos de conocimiento, para consultarlos utilice lo siguiente


    `https://autenticacion.portaloas.udistrital.edu.co/apioas/parametros/v1/parametro?query=ParametroPadreId:153&limit=0&fields=Id,Nombre,Descripcion,CodigoAbreviacion&sortby=Id&order=asc`

donde se busca por `ParametroPadreId` que es el id del área de conocimiento

también se recomienda modificar la consulta de áreas de conocimiento para que busque solo los que tengan `ParametroPadreId` en null
