### ISSUE TITLE
Identificar Parametros

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/necesidades_cliente#242]
De manera similar a lo realizado en
- udistrital/presupuesto_cliente#436
- udistrital/presupuesto_cliente#437

- [x] Identificar los parámetros asociados al cliente de Necesidades
- [x] Clasificarlos según si Necesidades tiene dominio o no sobre los parámetros identificados

**Comment by brayanpasa99** [comment]
Se tuvo un problema con el API de configuración que impide realizar el documento para la reunión que se llevó a cabo con María Claudia (@mcrubianot ) a las 8:00 AM, udistrital/financiera_documentacion#309, sin embargo, se tratan temas generales y contextualización con respecto al cliente de Necesidades con lo cual se espera elaborar el documento de parámetros y volver a pactar una reunión con María Claudia para finiquitar detalles y realizar los Mockup correspondientes.

**Comment by brayanpasa99** [comment]
Se genera un documento similar al utilizado para la parametrización del cliente, con el fin de discutir en la reunión de mañana los dominios de los diferentes campos y novedades con respecto a los parámetros de necesidades.

[Parámetros](https://www.notion.so/brayanpasa99/Identificaci-n-par-metros-necesidades-v1-0-59127adb91b448dd944697d68f3cf45a)

**Comment by brayanpasa99** [comment]
Después de reunión con María Claudia (@mcrubianot), se determina el dominio de los diferentes parámetros implícitos del cliente de Necesidades, se genera un documento final de este issue y se procede con la elaboración de Mockups para #243 . Se dejan notas en el documento en cada uno de los parámetros definidos y en la parte final con el contexto general entregado del cliente.

[Documento Parámetros](https://www.notion.so/brayanpasa99/Identificaci-n-par-metros-necesidades-v1-0-59127adb91b448dd944697d68f3cf45a)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
