### ISSUE TITLE
Interconexión Metas/Actividades

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/necesidades_cliente#250]
- [x] Identificar la petición que se está haciendo actualmente para la consulta (donde se está haciendo)
- [x] Mirar si se debe consultar un MID, un tr dentro del CRUD, o directamente el CRUD (que aplique) en relación al **Plan de Adquisiciones** (tratar de usar lo que esté)
- [x] Reemplazar la consulta vieja por la nueva

Tiempo estimado: 2d

**Comment by brayanpasa99** [comment]
En reunión con Daniel se encuentra que actualmente las peticiones se hacen en `app/scripts/directives` las cuales tienen vinculadas un servicio y una variable de entorno respectiva, queda pendiente analizar las solicitudes que realizan para Metas y Actividades, además de mirar dónde se están guardando estas mismas desde Plan de Adquisisiones.

**Comment by brayanpasa99** [comment]
En reunión con María Claudia se habla de un tema a tener en cuenta, debido a que en la reunión con Planeación llevada a cabo el día lunes se planteó la posibilidad de cambiar la forma como se almacenan y extraen los datos de: Metas, Actividades y Fuentes de Financiamiento.

**Comment by brayanpasa99** [comment]
Para este issue será necesario solicitar el acceso de Necesidades a Plan de Adquisisiones:

![ErrorCORS](https://user-images.githubusercontent.com/42362278/130493714-dc29ba96-3725-4101-a275-d9f67935a1bc.png)

**Comment by haplo103** [comment]
Se informa que se han otorgado permisos para Necesidades al Plan de Adquisiciones, por favor confirmar, muchas gracias

**Comment by brayanpasa99** [comment]
> Se informa que se han otorgado permisos para Necesidades al Plan de Adquisiciones, por favor confirmar, muchas gracias

Confirmado el acceso. Gracias.

**Comment by brayanpasa99** [comment]
Se realiza el cambio por la nueva API referente a Plan de Adquisisiones, la sección de la aplicación del cliente queda de la siguiente manera:

![MetasyActividades](https://user-images.githubusercontent.com/42362278/131071553-aa43794a-48d1-4538-a5c8-eba9c8e034ad.png)

Se realiza un merge con la rama de @DanKazuky para obtener el listado de planes de adquisisión y poder traerlos todos de manera correcta.

Tareas pendientes:

* [ ] Eliminación de código innecesario
* [ ] Verficación de la validación del monto de las fuentes de financiamiento
* [x] Cambiar la Vigencia por defecto a una Vigencia que se desprenda del Plan de Adquisisiones seleccionado
* [x] Cambiar el Rubro de manera dinámica dependiendo la selección en la tabla

**Comment by brayanpasa99** [comment]
Se da cierre a este issue teniendo en cuenta que se asigna una nueva actividad relacionada con dependencias en #256, allí se deberá verificar el código que quedó comentado relacionado con las verificaciones que implican observar las dependencias, por otro lado, queda pendiente revisar la forma como se realiza la validación del monto de las fuentes de financiamiento, teniendo en cuenta que hay cosas que deben venir de presupuesto y otras del plan de adquisiciones.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
