### ISSUE TITLE
Interconexión Rubros

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/necesidades_cliente#251]
- [x] Identificar la petición que se está haciendo actualmente para la consulta (donde se está haciendo)
- [x] Mirar si se debe consultar un MID, un tr dentro de un CRUD, o directamente un CRUD (que aplique) en relación a **Presupuesto** (tratar de usar lo que esté)
- [x] Reemplazar la consulta vieja por la nueva (si aplica)

Puede que tenga relación con udistrital/presupuesto_cliente#446

Tiempo estimado: 2d

**Comment by DanKazuky** [comment]
La petición que se hace para consultar los rubros se realiza en lista_apropiaciones.js, donde este tiene un $watchgroup que consulta dependiendo de la unidad ejecutora y el tipo de financiación.

Este realiza una consulta con estos datos a plan_cuentas_mongo_crud con el siguiente enlace:
https://autenticacion.portaloas.udistrital.edu.co/apioas/plan_cuentas_mongo_crud/v1/

Para el funcionamiento correcto se requiere que se agregue como parametros unidad ejecutora y la vigencia, por ahora este realiza un correcto funcionamiento a diferencia del cliente de presupuesto que realiza consulta a bodega_jbpm. Se deja en consulta para definir si se debe cambiar.

**Comment by DanKazuky** [comment]
Se identifica que la consulta a plan de cuenta mongo crud es la donde se están guardando los rubros en presupuesto, sin embargo la razón por la que no se ve reflejado lo que se guarda en presupuesto a necesidades, es la vigencia que se encuentra quemada en el código en ambos clientes con fechas diferentes.  Se comenta lo descubierto para poder generar un nuevo Issue sincronizando la vigencia en los clientes.

No se realizan cambios en la consulta por lo que esa es la que se debe realizar.

**Comment by AlexFBP** [comment]
Tener en cuenta que el contenido del documento "convenios" de udistrital/financiera_documentacion#349 es lo que debería de mostrarse en la vista de Rubros

![image](https://user-images.githubusercontent.com/6588872/130288335-c81a754d-4b0a-434f-994a-c218adb6ed09.png)

CUANDO: Tipo Financiacion = Funcionamiento Y Area funcional = convenios

**Comment by DanKazuky** [comment]
Según lo analizado, se agregara una nueva tarea para poder solucionar el inconveniente (Este quedara bajo análisis y comentarios del Scrum master).

- [x]  Hacer uso del API de plan de adquisiciones CRUD en el cliente para obtener los planes de adquisidores que harán llamado de la vigencia al consultar los rubros.

**Comment by DanKazuky** [comment]
Se creo el service para consumir el servicio de plan_adquisiciones_crud, este se consume en solicitud_necesidad y se deja el endpoint en los enviroment.
En el index se ajusto para guardar el dato seleccionado en vigencia y se verifica que funcione correctamente. Se adiciono el script en el index del servicio del plan de adquisiciones como se especifico  y así consultar los rubros de forma exitosa.

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial
