### ISSUE TITLE
Filtrar plan de adquisición según el contexto

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/necesidades_cliente#257]
HOLD: Depende de 
- DEP1: Items 1 y 2 de udistrital/plan_adquisiciones_cliente#81
- DEP2: #256

Traer datos - Cruzar información entre los CRUD de configuracion y parametros, y DEP2, para ...
- [x] 1. DEP1_1: ... traer el plan de adquisiciones activo
- [x] 2. DEP1_2: ... traer el plan de adquisiciones a ser usado por el Idexud

No deberían de aparecer todos los planes de adquisiciones, deberían de aparecer según el contexto ...:
- [x] 3. (Depende de 1.) ... para alguien que NO sea del Idexud* (area_funcional: rectoría?)
- [x] 4. (Depende de 2.) ... para alguien que SI sea del Idexud* (area_funcional: convenios? --> idexud?)
- [x] 5. (Depende-de/complementa-a 4.) Para el idexud, automáticamente:
      - Tipo de Financiación: Seleccionar Funcionamiento?
      - Área Funcional: Seleccionar Convenios?
      - Plan de Adquisiciones: Ocultar este campo? o basta con desactivarlo?

A tener en cuenta:
- El desarrollo deberá realizarse de tal manera que permita a futuro aplicar restricciones arbitrarias a la interfaz (por ejemplo, del modo que se describe en 3. - 5.) según el área funcional
- Confirmar los "?" con Analista

**Comment by AlexFBP** [comment]
@brayanpasa99 De este Issue haz 1. y 2. tan pronto acabes 1. y 2. de udistrital/plan_adquisiciones_cliente#81

**Comment by brayanpasa99** [comment]
Actualmente se realizan los cambios acordes con 1, 2, 3 y 4 con el fin de desplegar la lista de planes de adquisición según el Área Funcional (dependencia seleccionada), se espera realizar integración con #256 y se hace uso del parámetro creado en configuración de acuerdo con udistrital/plan_adquisiciones_cliente#81, se dejan capturas de la interfaz actual

![PlanAdquisicionesRector](https://user-images.githubusercontent.com/42362278/132739589-4ed7d00a-166d-4851-9256-3cae6e1ebcdc.png)

Para el Plan de Adquisiciones del IDEXUD se trae un valor undefined dado que ese plan aún no está definido.

![PlanAdquisicionesIDEXUD](https://user-images.githubusercontent.com/42362278/132740123-fb4e72f2-38b1-4dc3-8652-3df889cf68b5.png)

**Comment by AlexFBP** [comment]
En conversación con @brayanpasa99 se concluye que es posible que mas adelante (y para reducir/eliminar "código quemado") hagan falta las siguientes tablas en plan_cuentas_mongo_crud (omitiendo los campos mínimos del [lineamiento](https://github.com/udistrital/lineamientos_oas/blob/master/modelo_de_datos/estandar.md#columnas)): 

## `tipo_vinculo`
Tipos de vínculos
| id | nombre | descripcion | instrucciones_vinculo |
| --- | --- | --- | --- |
| 1 | "area_funcional" | "Areas funcionales (anteriormente: Unidad Ejecutora)" | "id de PARAMETROS_CRUD/parametro" (ejemplo) |

## `vinculo_rama_arbol_rubros`
Para registrar cualquier vínculo con una rama del árbol de rubros

|tipo_vinculo_id | valor_vinculo | rama_arbol_rubros_id |
| --- | --- | --- |
| 1 | "1" (1)| (7) "3-01" |
| 1 | "1" (1)| (7) "3-02" |
| 1 | "2" (2)| (7) "3-00" |

(1) - Suponer que corresponde a rectoría
(2) - Suponer que corresponde a convenios
(7) - El id que corresponda a...

## `dependencia_area_funcional`
Solo en caso que no exista (posiblemente se pueda obtener de otra forma en oikos), para listar las relaciones entre dependencias y áreas funcionales (anteriormente: unidades ejecutoras) se podría crear la siguiente tabla de rompimiento

| area_funcional_id | dependencia_id |
| --- | --- |
| "1" (4) | "56" (3) |
| "2" (6) | "56" (5) |

(3) - Suponer que corresponde al ID de la OAS
(4) - Suponer que corresponde al ID de rectoría
(5) - Suponer que corresponde a un ID de una dependencia vinculada al Idexud
(6) - Suponer que corresponde al ID del Idexud

**Comment by brayanpasa99** [comment]
Para el tema del árbol de rubros fue necesario agregar dos validaciones más en los hijos para que no hiciera el forEach si el valor era nulo. No sé si sea la mejor solución porque la variable nivel no sé a qué corresponde, de momento está mostrando el árbol así como en la imágen

![Rubros](https://user-images.githubusercontent.com/42362278/133823938-5e6b0cd4-5ac2-4c57-8e86-6165f9a623f8.png)

Asimismo, la preasignación funciona como se muestra 

![Preasignacion](https://user-images.githubusercontent.com/42362278/133823984-c5cab7cc-3345-40ed-8626-2f97e92f8aaa.png)

**Comment by brayanpasa99** [comment]
En reunión con Alex se decide hacer una deshabilitación de los campos para no tener una validación errónea al crear la solicitud de necesidad, estos campos quedan de la siguiente manera:

![SinAreaFuncional](https://user-images.githubusercontent.com/42362278/133824120-9c041c8b-630f-41cf-83b4-f97d86b34154.png)

![AreaRector](https://user-images.githubusercontent.com/42362278/133824153-3af2c295-15c9-42bc-a516-7ac568b25484.png)

![AreaIDEXUD](https://user-images.githubusercontent.com/42362278/133824173-62efc974-d906-4af5-8f33-3dfb9d1bc90a.png)
