### ISSUE TITLE
Socialización de cliente de Necesidades

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades_cliente#26]
Se realiza una socialización del cliente de necesidades comentando los ajustes realizados sobre el formulario con la Analista @mcrubianot .

**Comment by mcrubianot** [comment]
Se hacen las siguientes observaciones.
- En el mockups cuando se hace una compra, se debe totalizar por Subtotal, Total iva, Total.
- En el mockups de "Contrato de prestación de servicios" me parece que no debería definirse de una vez el tipo de contrato por el usuario solicitante por que ese lo define es el ordenador del gasto. Considero que el Título de este recuadro sea " Clase de Contratación" y posteriormente de acuerdo a la aprobación de dicho documento, si desplegar un "Tipo de contrato"

**Comment by macaguegi** [comment]
Se tienen en cuenta estas correcciones para los ajustes que se harán esta semana sobre el cliente de necesidades.

**Comment by mcrubianot** [comment]
Se realiza sesión de trabajo con algunos usuarios y se hace necesario tener en cuenta las apreciaciones planteadas en el acta correspondiente.

https://docs.google.com/document/d/1Qk9z7IWx11rtHLpyzE-m5g-aV1tRz2d1UKXmcb5dguo/edit

**Comment by Soulfilip-UD** [comment]
Se abstrae que las modificacciones a realizar son:

- [ ] La opción de 'Ùnico pago' y 'Hasta agotar presupuesto' van con la opción de especificar una duración, asimismo vendra con un label adicional para evitar confusiones . "En caso de que tenga duración, especificarla"

- [ ] Validación del formulario por sección

- [ ] Incluir en el formulario las metas y las actividades

- [ ] Anexar el valor por acttividad y por producto 

- [ ] Visualizar las fuentes de financiamiento, revisar que hayan rubros asociados a una fuente

- [ ] Al desplegar clase de contratación ' Compra y servicio' esta parte de formulario, debe tener el catalogo de compras, retirar las opciones para especificar el perfil de la persona, y anexar un select que liste el tipo de servicio (este se alimenta de un servicio ya creado)

- [ ] Al consultar una necesidad anexar al modal las metas y actividades

- [ ] Al aprobar una necesidad se debe seleccionar el tipo de contrato modalidad

- [ ] Poder Editar una necesidad ( de está se debe asimismo crear la historia de usuario, ya que no se habia planteado)

- [ ] Al consultar una necesidad se puede generar un pdf, arreglar los detalles de este ya que parece no funcionar

- [ ] Actualizar los datos de las necesidades generadas ya hace rato, ya que al encontrar inconsistencias el sistema lista un espacio en blanco.

- [ ]

**Comment by Soulfilip-UD** [comment]
Asociemos todos los Issue referentes al trabajo que se ha ido trabajando , la tarea no se cierra hasta que se finalize con los checkbox y se socialize de nuevo con el usuario los cambios

**Comment by Soulfilip-UD** [comment]
Se han finalizado varios ajustes y este viernes por parte del equipo de desarrollo de necesidades nos reuniremos para una última revisión, más el desarrollo está listo para ser socializado de nuevo con el usuario

**Comment by macaguegi** [comment]
En socialización del cliente de Necesidades se concertan junto a la analista @mcrubianot las siguientes observaciones :

- [ ] No permitir registrar una necesidad si faltan secciones del formulario

- [ ] Los valores de Financiación deben coincidir con los valores de Clase de Contratación

- [ ] En la consulta de una solicitud de necesidad aprobada debe visualizarse el tipo de contrato y la modalidad de seleccion del mismo

**Comment by Soulfilip-UD** [comment]
Se continua con los siguientes ajustes #68 Ajustes cliente de necesidades

**Comment by Soulfilip-UD** [comment]
Ajustes finalizados y desarrollo listo para ser revisado por el usuario de nuevo.

**Comment by Soulfilip-UD** [comment]
Se cierra el Issue hasta entonces
