### ISSUE TITLE
Ajustar Interfaz, Paso 2 en Solicitud Necesidad

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/necesidades_cliente#271]
## Consideraciones / Referencias

- Se logró la conexión con el Plan de Adquisiciones, específicamente para traer los planes de adquisiciones publicados

## Ajustar

Vistas de

- [x] Rubros
- [x] Fuentes
- [x] Actividades
- [x] Metas
- [x] Productos

**Comment by brayanpasa99** [comment]
Se realiza el ajuste de la variable para llenar los datos según se hacía en el cliente, con esto se obtiene que las metas de los rubros son traídas según lo tratado en issues anteriores, es necesario cambiar la solicitud que se está haciendo a metas y actividades para que esta sea acorde con los datos que se traen del plan de adquisición.

![AvanceMetas](https://user-images.githubusercontent.com/42362278/137559309-15ed9f92-5791-482c-8118-2b955d592eed.png)

![AvanceMetas](https://user-images.githubusercontent.com/42362278/137559332-68753d15-9b43-4062-8f22-f5aa25020706.png)

**Comment by brayanpasa99** [comment]
**Novedades:** Las metas y actividades se están trayendo correctamente, frente a este aspecto queda pendiente revisar ciertas validaciones y código comentado (que al parecer no afecta funcionalidad) antes de borrarlo

![AvanceActividades](https://user-images.githubusercontent.com/42362278/137936419-6b936f47-3815-49fd-a26f-2f7087a1914d.png)

Las fuentes de financiamiento se están trayendo de manera correcta, queda pendiente revisar en especial una línea de código que tiene fallos (al parecer no afecta funcionalidad), queda comentada

![AvanceFuentes](https://user-images.githubusercontent.com/42362278/137936725-a46ffd62-2988-4dee-8e4b-0746f0ed29d5.png)

**Problema:** Se presenta el error de la siguiente imágen al intentar continuar con la solicitud de necesidad, es necesario revisar

![ErrorSiguiente](https://user-images.githubusercontent.com/42362278/137936909-bd5e0a2a-ac84-4a31-b327-870848bdc5fe.png)

**Pendientes:** 
* Revisar líneas de código comentadas
* Solucionar la conexión de los productos dado que esta se da de forma diferentes con respecto a las metas, actividades y fuentes de financiamiento
* Revisar error al presionar siguiente en la solicitud de necesidad

**Comment by brayanpasa99** [comment]
**Novedades:** Los productos se traen de manera correcta, se añaden los campos de código del producto y su porcentaje de distribución con respecto al código que había antes

![AvanceProductos](https://user-images.githubusercontent.com/42362278/137952746-2fa89762-6976-4280-aa1f-94a4a7d92308.png)

**Comment by brayanpasa99** [comment]
**Novedades:** Después de reunión con María Claudia (@mcrubianot) se confirma que el ValorInicial del Rubro debe ser el ValorActual de la comparación que generaba problemas, se hace el cambio y en este momento se hace la validación correctamente.

![ValorActual](https://user-images.githubusercontent.com/42362278/138137766-e0a85c3c-6985-4803-bd3e-6ee48df04efb.png)

En la misma reunión se concibe que la tabla de Actividades Económicas debe mostrar el código CIIU y no el identificador que venía en la data, se realiza el respectivo cambio.

![CodigoCIIU](https://user-images.githubusercontent.com/42362278/138137978-392842fb-27d9-4518-96f7-92d0d33a5efc.png)

**Comment by AlexFBP** [comment]
Se cierra de acuerdo al historial. La propagación y/o validación de valores de los rubros se tratará en https://github.com/udistrital/presupuesto_cliente/issues/468
