### ISSUE TITLE
Ajustar Interfaz Necesidad, Pasos 3 y 4 de Solicitud de Necesidad

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/necesidades_cliente#272]

**Comment by DanKazuky** [comment]
Se realizo la revisión en pruebas de necesidad de los pasos 3 y 4, se encontró que el cliente esta funcionando con el desarrollo actual sin inconvenientes, sin embargo como se planean hacer desarrollos pendientes para la entrega, se deja abierto para realizar una nueva validación después de terminar los desarrollos/arreglos pendientes.

**Comment by DanKazuky** [comment]
Se termino de realizar la revisión conforme a los pasos 3 y 4 de la creación de necesidad, se determino que cada paso ejecuta sus tareas de manera correcta sin presentar inconvenientes, el paso a seguir fue revisar los datos que se envían a ser registrados por la necesidad y se identifica que se debe validar la información que se debe registrar para posteriormente ser consultada, ya que con los cambios que se han ido realizando la estructura de la información difiere de como se manejaba antes de los cambios, para que no hayan conflictos se revisara y ajustara y así realizar el registro exitosamente y sin perdidas de información.

También se desea ajustar la vista de la edición de la necesidad una vez este registrada, para esto se revisara el siguiente modulo desarrollado que es la consulta de la necesidad y junto con los ajustes que se realicen al registro de la necesidad, estos serán ajustados.
