### ISSUE TITLE
Hallazgos Noviembre 2021

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/necesidades_cliente#286]
## Consideraciones / Referencias
- [Inventario de Desarrollos](https://docs.google.com/spreadsheets/d/1Y9kywbToMgAzTDd8btist4mktgVEf1CsgmkIiCIWgHE/edit#gid=1399888419)
- [Apuntes Brayan](https://cdn.discordapp.com/attachments/857652587393318922/906042139568373770/Tareas_Necesidades.pdf)

## Ajustar

Prioridad: A: Alta - M: Media - B: Baja

### Solicitud

- [x] (P:A) Validar monto de la fuente al asignar
- [x] (P:??) Advertencia Datos
- [ ] (P:B) Interventores/Dependencias(+Ordenador del Gasto) con autocompleter
- [ ] (P:N/A-M/A) Ajustar para que el vicerrector, cuando se escoja como ordenador del gasto, traiga el nombre
- [ ] (P:A) Ajustar (desde el cliente) que no se pueda tomar más de la fuente (ej, es de 5, se puede colocar actualmente 10, no debería!) (En inversión)

### Ver (Unicamente, NO editar)

- [ ] (P:B) Respecto al rubro, no es necesario mostrar el valor, quitarlo de la vista
- [ ] (P:A) Mostrar nombres de metas, actividades y fuentes
- [ ] (P:AA) Al aprobar la necesidad, actualizar valores de: Fuentes/Actividades/Metas/Rubros - "Descontar los valores correspondientes y los del mismo rubro para futuras aprobaciones"
- [ ] (P:??) Restringir la aprobación de la necesidad  (jefe dependencia? ordenador gasto?) --> Crear Issue @AlexFBP

**Comment by brayanpasa99** [comment]
Según lo acordado se realizan modificaciones de la siguiente manera:

* El monto de la fuente a asignar era un inconveniente de presupuesto al cual se llegó a una conclusión gracias a la ayuda de María Claudia y es que esta fuente al ser creada por primera vez no tiene ningún otro valor de respaldo el cual pueda generar inconvenientes así que se deja como estaba
* El select se arregla en cuanto a dimensiones y los datos solicitados
* El problema de leer las actividades en fuentes de financiamiento se soluciona deshabilitando el selector de fuentes hasta que se seleccione la actividad vacía en el selector e actividades, fue la manera más conveniente de solucionar
* Se realizan las validaciones para poder finalizar el proceso de guardado o agregado del rubro deshabilitandolo y mostrando un aviso si el valor asignado a la fuente supera el monto previsto para el rubro
* La advertencia de datos aparece en ocasiones efímeras y no es objeto de este issue además que no fue una falla concurrente
* Que se pueda seleccionar más de una fuente para gastos de funcionamiento (rubros) fue un tema que se trató, pero que se acordó para iteraciones posteriores dado que tiene una complejidad mayor a la de las otras tareas... Conveniente mover a un issue siguiente para dar por finalizado este y mostrar el progreso en el informe de gestión

**Comment by brayanpasa99** [comment]
Hallazgo sobre actualización de valores al aprobar la necesidad:

* Se realiza la inspección al proceso de aprobación, pero no se encuentra nada relacionado con la actualización de valores,por lo cual queda la duda sobre la mesa de dónde se debe a hacer la actualización.
* Se plantea la duda sobre dónde deberían actualizarse los valores (a qué nivel), si en el plan de adquisiciones, en presupuesto u otros (o solo uno de ellos). Esta duda se presenta dado que los datos se traen de plan de adquisiciones, pero también del árbol de apropiación por mencionar algunos y se busca tener consistencia entre los diferentes datos.
