### ISSUE TITLE
necesidades cliente: Agregar más de un apropiación a la parte de financiación

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_cliente#46]
- [x] revision del flujo actual de agregar apropiacion
- [x] correccion de las funciones que controlan la lista de apropiaciones segun los nuevos servicios de financiera
 - 8 horas - Carlos

**Comment by Soulfilip-UD** [comment]
Gracias Carlos, se revisa la tarea. Hay un pequeño detalle con una alerta que le hace falta revisar ortografía en el PR#48, quedo señalado en el review para que se solucione y se vuelva revisar

**Comment by Soulfilip-UD** [comment]
Errores corregidos en un PR posterior
Tarea finalizada

Proceeding to close Issue 👾
