### ISSUE TITLE
necesidades_cliente: Ajustar al guardar necesidad desde el cliente para que guarde en plan_cuentas y administrativa

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_cliente#56]
- [x] Armar el objeto necesidad
- [x] Guardarlo en ambas partes 
- 8 horas - Carlos

**Comment by CarlosGutierrezArdila** [comment]
2/09/2019: se estudian estrategias para armar la transaccion con promesas desde el cliente para las 2 APIS asi como el registro de los objetos, se verifica que las apis esten en test y se espera a tener funcionalidad en cliente para continuar con la tarea, 15%

**Comment by CarlosGutierrezArdila** [comment]
04//09/2019: Se ajustan cosas en financiación, metas y actividades, se esta a la espera de que todas las apis respondan correctamente para enviar el post 40%

**Comment by macaguegi** [comment]
05/09/2019: Se arma el objeto para enviar el post a plan cuentas, pendiente por errores de api administrativa crud (permisos) 70%

**Comment by Soulfilip-UD** [comment]
Se reviso en la tarde del jueves con el dba se reviso el usario y permisos, pero se debe ser más especifico del esquema y tablas que se modifican para que el pueda continuar ayudandonos, por lo que se debe revisar estos datos directamente desde el API de administrativa_crud

**Comment by CarlosGutierrezArdila** [comment]
9/9/19:  se realizan los detalles finales en el flujo de guardado, y es funcional siempre y cuando las dos peticiones salgan bien, se debe evaluar manejo de transaccionalidad puesto que el delete en administrativa no es trivial al ser un modelo relacional, sin embargo se culmina la funcionalidad y se deja para revision de LT @soulfilip

**Comment by Soulfilip-UD** [comment]
el manejo de la transaccionalidad es algo que aseguran los qrquitectos de la oficina, y mas especificamente es la implementación de un broker que se hara por parte del equipo del core, así que se da la tarea por finalizada ya que está solo se refiere al desarrollo

Proceeding to close Issue 👾
