### ISSUE TITLE
necesidades_cliente: Cambiar las urls de las APIs 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_cliente#57]
- [x] inventario de las APIS que usa el cliente
- [x] verificar que las apis esten en preprod
- [x] solicitar que esten en preprod,  verificar variables de entorno , y cambiar las url 
- ? horas - Carlos , Camila, Felipe

**Comment by macaguegi** [comment]
Se verifican las APIs que son usadas por Necesidades Cliente y se revisa que estén en el ambiente TEST. El equipo de administrativa nos comparte un documento del estado actual de las APIs en Preproducción [Revisión APIs](https://docs.google.com/spreadsheets/d/1P88BMq0Js1qm2hNjbi9qNq1JStGe7jZNzX3DGXpi1A4/edit?ts=5d6d639f#gid=0) .

El líder técnico @Soulfilip-UD gestiona el token de autenticación para el cliente.

Con el desarrollador @CarlosGutierrezArdila se está a la espera de asignación de roles a usuario para poder validar que todos los servicios se estén consumiendo correctamente.

Estado de la tarea : 50%

**Comment by Soulfilip-UD** [comment]
Se identifica las APIs con las que cuenta el cliente de necesidades en el caso especifico de : 

- [ ] oikos_crud_api ( tarjeta tuleap : despliegue1 #32338
Realizar despliegue de oikos_api en ambiente test )

- [ ] core_api ( tarjeta tuleap: despliegue1 #32330
Realizar despliegue de core_api en ambiente test)

se confirma que ya está en gestión el despliegue correcto de estas en el ambiente de test.

Para el API de plan de cuentas se sugiere trabajarlo en local y el seguimiento del despliegue de este en test se puede revisar en el Issue [78](https://github.com/udistrital/plan_cuentas_mongo_crud/issues/78)

**Comment by Soulfilip-UD** [comment]
Con el arquitecto se realizo la tarea de revisar los APIs que necesitaban los clientes, que nombre tienen registrados en WSO2 y se registraron a la aplicación.
[Link referencia de APIs](https://docs.google.com/spreadsheets/d/1P88BMq0Js1qm2hNjbi9qNq1JStGe7jZNzX3DGXpi1A4/edit#gid=497832981), 2da pestaña 'registro APIs en el sp'

Core_api me avisa el lider del core (Fabio) ya está arriba, debemos revisar y suscribirla a la aplicación.

**Comment by Soulfilip-UD** [comment]
La solución de este último error se soluciona en el siguiente Issue y ya no es responsabilidad del equipo sino gestión por parte del lider.

Tarea realizada
Proceeding to close Issue 👾
