### ISSUE TITLE
Modificar la consulta del estado de las necesidades

### ISSUE THREAD

**Issue by macaguegi** [udistrital/necesidades_cliente#62]
Se solicita traer la información de Plan Cuentas Mongo (Necesidades) y : 

- [x] Actualizar información de Rubros en formulario de Consulta

- [x] Actualizar información de Fuentes de Financiamiento en formulario de Consulta

- [x] Actualizar información de Productos en formulario de Consulta

Despues de que el Ordenador del Gasto  Apruebe una Solicitud de Necesidad 
- [x] Actualizar información de Modalidad de Selección en formulario de Consulta

- [x] Actualizar información de Tipo de Contrato en formulario de Consulta

**Comment by macaguegi** [comment]
Se trabaja en esta tarea y se avanza un 80% cargando la información de Financiación que proviene de Plan de Cuentas Mongo.

**Comment by macaguegi** [comment]
La parte de financiación se ajusta y consulta la información de la solicitud de Necesidad 
![image](https://user-images.githubusercontent.com/12780939/64635043-584cf500-d3c4-11e9-94ae-fa57ee24f1b6.png)

**Comment by macaguegi** [comment]
Se trabaja en esta tarea y se deja en un 90% hasta el día de hoy.

**Comment by macaguegi** [comment]
Se cierra esta tarea confirmando la visualización de Clase de Contratación y Modalidad de Selección para una solicitud **APROBADA** . Estado : 100% . Se solicita revisión de @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Se desplego en la rama test los cambios y se revisaron los cambios.
Tarea finalizada 
Proceeding to close Issue 👾
