### ISSUE TITLE
necesidades cliente: Actualizar el estado de las necesidades ( Modificación sobre el Cliente PUT) 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_cliente#63]
-  modificacion del flujo de actualizacion de necesidad para que se actualice el objeto de plan cuentas
- 5 horas - Carlos

**Comment by CarlosGutierrezArdila** [comment]
9/9/19: se resuelven temporalmente problemas en post y put por fallas de logica en API administrativa (asignaciones basadas en Ids fijos de bases de datos anteriores) y se realizan pruebas de transaccionalidad en POST  avance 10%

**Comment by CarlosGutierrezArdila** [comment]
tarea finalizada 100%

**Comment by Soulfilip-UD** [comment]
Perfecto el código está quedando limpio.

Tarea revisada y finalizada
Proceeding to close Issue 👾
