### ISSUE TITLE
Ocultar el botón de cambio de idioma y menus de CDPs y CRPs. 

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_cliente#67]
- [x] Ocultar el botón de cambio de idioma y menus de CDPs y CRPs. 
30 min

**Comment by CarlosGutierrezArdila** [comment]
tarea finalizada 100% se deja para Revision LT @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Tarea revisada y desplegada

Proceeding to close Issue 👾
