### ISSUE TITLE
Ajustes cliente de necesidades

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_cliente#68]
Tomando en cuenta las sugerencias de la ultima socializacion se plantearon los siguientes ajustes:
- [x] Cargar información de plan cuentas mongo crud en la edición de la necesidad - 10 horas
- [x] Quitar el botón de Atrás en el primer TAB . Arreglar estilos del formulario 5 horas
- [x] Al aprobar y rechazar la necesidad que se cierre el modal y se actualice la tabla - 3 horas
- [x] Cuando esté rechazada que no salga modalidad de selección ni tipo de contrato 3 horas
- [x] En el modal de consulta de necesidad . Se debe removar el numero de elaboración y poner el numero de necesidad . Agregar vigencia y quitar numero de CDP si no ha sido solicitado 3 horas
- [x] En la Consulta de Necesidades se debe mostrar solamente Consecutivo, Vigencia y Centro Gestor. 5 horas
- [x] El servicio deberia tener un valor (Compra y Servicio) para ser sumado con los productos - 3 horas
- [x] Justificar texto de moneda a la derecha - 2 horas
- [x] Revisar usabilidad de elementos de compras (Minimizar y hacer prolijo lo de productos) - 5 horas
- [x] Limpiar los datos de Marco legal . 2 horas
- [x] Filtrar los rubros por financiamiento e inversión, solos los rubros 3 están relacionados a gastos. 5 horas

- [x] Filtrar metas y actividades según la dependencia - 2 horas

- [x] Supervisores Agregar CARGO + NOMBRE en el select - 2 horas

**Comment by Soulfilip-UD** [comment]
Cambios previos en el Issue #26

**Comment by macaguegi** [comment]
Se concluye esta tarea . Estado : 100% . Se solicita revisión por parte de líder técnico @Soulfilip-UD

**Comment by Soulfilip-UD** [comment]
Se reviisa el PR , se aprueba y se despliegan los cambios sobre la versión en test.
Tarea finalizada y revisada .
Buen trabajo

Proceeding to close Issue 👾
