### ISSUE TITLE
Ajustes de necesidades de acuerdo a analista

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_cliente#85]
- [x] realizar ajustes encontrados en cliente de necesidades cuando se realice la revison
 -? horas - Carlos

**Comment by CarlosGutierrezArdila** [comment]
Se realizan los ajustes https://github.com/udistrital/necesidades_cliente/pull/87/commits/b7c70e6e9a0732d35ee076ccfad1d310505c17d1 y https://github.com/udistrital/necesidades_cliente/pull/87/commits/a054a9b1ad89dbbc312c7d8ee65a44ca3510186f Solicitados por LT 2H

**Comment by Soulfilip-UD** [comment]
Debemos revisar el documento realizado por el @mcrubianot, se realizara con una pequeña reunión para estar bien enterado cuando ocurrio el error, la reunión lo mejor es realizarla el viernes 4 de Octubre, 
Estado de la tarea en el momento con los ajustes adelantados 10%

**Comment by CarlosGutierrezArdila** [comment]
Ajustes pendientes :
- [ ] Los supervisores deben ser de planta
- [ ] Al recibir un null de rol ordenador de gasto, no vuelve a actualizar
- [ ] centro gestor -> area funcional
- [ ] hay un valor por defecto de 100000 en la fuente?
- [ ] los valores de fuente y productos alinearlos los 2 al fondo a la derecha
- [ ] la caja del producto, falta el el valor total = subtotal + iva
- [ ] botón caja de producto detalle, que de a entender que se guardo la info Y actualize el valor servicio + producto
- [ ] limpiar siempre texfield s cuando intercambio entre  clase de contratación
- [ ] no finaliza el registro de una necesidades por servicio públicos

**Comment by Soulfilip-UD** [comment]
Bug detectado mientras se realizaba la revisión aún se desconoze como replicarlo y la razón, el modal surge al finalizar el proceso de registrar la necesidad, se noto que crea la solicitud de una necesidad más deja los datos incompletos.
![image (3)](https://user-images.githubusercontent.com/50924615/66461059-cde8c700-ea3d-11e9-95fe-a2c9da3ba13a.png)

**Comment by Soulfilip-UD** [comment]
6/9 items solucionados a la fecha .

66,6% de la tarea realizada, @CarlosGutierrezArdila no olvide al finalizar la tarea poner el número total de horas realizando la tarea.

**Comment by CarlosGutierrezArdila** [comment]
Se solicita a LT @Soulfilip-UD revisar el cierre de este issue con los ajustes que se realizaron sobre https://github.com/udistrital/necesidades_cliente/issues/107

**Comment by Soulfilip-UD** [comment]
Varios cambios se suben y se ajustan con el PR #115 , quedan un par de detalles por solucionar en el PR cuando se solucionen actualizo la rama test para la revisión del despliegue en test.

Aún así la tarea se ha completado en un 100% y los ajustes han sido revisados previamente en local, por lo que apenas despliegue se estima que la tarea se puede cerrar inmediatamente 
@CarlosGutierrezArdila  @macaguegi

**Comment by Soulfilip-UD** [comment]
Tarea revisa y finalizada
Proceeding to close Issue 👾
