### ISSUE TITLE
Registrar una solicitud de CDP

### ISSUE THREAD

**Issue by CarlosGutierrezArdila** [udistrital/necesidades_cliente#86]
- [x] actualizar la funcionalidad de necesidades para realizar una solicitud de CDP a los nuevos servicios
 - 8 horas - Carlos

**Comment by CarlosGutierrezArdila** [comment]
Tarea finalizada 100% para revision de LT @Soulfilip-UD 9H

**Comment by Soulfilip-UD** [comment]
Desarrollo revisado y aprobado, asimismo se revisa la tarea desde el cliente y aprobado.

Tarea Finalizada
Proceeding to close Issue 👾
